inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - Gemfile

# 日本語のコメントを OK とする
Style/AsciiComments:
  Enabled: false

# 一行に 120 文字まで書いても OK とする
Metrics/LineLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false